version: "3.7"

services:
  bitapp:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - "/home/mixa/Documents/web/main/musbit/backend:/app"
      - /app/node_modules
    depends_on:
      - mysql_server
      - phpmyadmin
            
  mysql_server:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data_musbit:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=musbit
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data_musbit: 

